export const disneyData = [
  { id: "lampe", nom: "Lampe d'Aladdin", univers: "Aladdin", description: "Une lampe magique abritant un génie capable d'exaucer trois vœux." },
  { id: "pomme", nom: "Pomme empoisonnée", univers: "Blanche-Neige", description: "Une pomme d'apparence délicieuse, préparée par la Méchante Reine." },
  { id: "chausson", nom: "Pantoufle de verre", univers: "Cendrillon", description: "Le soulier perdu qui permet au Prince de retrouver Cendrillon." },
  { id: "rose", nom: "Rose enchantée", univers: "La Belle et la Bête", description: "Une rose dont les pétales tombent, marquant le temps qu'il reste à la Bête." },
  { id: "couronne", nom: "Couronne d'Aurore", univers: "La Belle au Bois Dormant", description: "La couronne royale de la princesse Aurore." },
  { id: "coquillage", nom: "Coquillage d'Ursula", univers: "La Petite Sirène", description: "Le pendentif magique utilisé par Ursula pour emprisonner la voix d'Ariel." },
  { id: "tasse", nom: "Zip (Tasse)", univers: "La Belle et la Bête", description: "Le petit fils de Madame Samovar, transformé en tasse à thé." },
  { id: "chapeau_mickey", nom: "Chapeau de Magicien", univers: "Fantasia", description: "Le chapeau puissant emprunté par l'Apprenti Sorcier Mickey." },
  { id: "arc", nom: "Arc de Merida", univers: "Rebelle", description: "L'arc emblématique de la princesse celte experte en tir." },
  { id: "poele", nom: "Poêle à frire", univers: "Raiponce", description: "L'arme de défense inattendue et redoutable de Raiponce." },
  { id: "ballon", nom: "Ballon Pixar", univers: "Pixar", description: "Le célèbre ballon jaune à étoile rouge, icône des studios Pixar." },
  { id: "botte", nom: "Botte avec plante", univers: "Wall-E", description: "Le symbole de l'espoir et du retour de la vie sur Terre." },
  { id: "guitare", nom: "Guitare d'Ernesto", univers: "Coco", description: "La guitare légendaire qui permet de voyager au Pays des Morts." },
  { id: "masque", nom: "Masque de Baymax", univers: "Les Nouveaux Héros", description: "Le visage du robot infirmier le plus attachant de San Fransokyo." },
  { id: "voiture", nom: "Flash McQueen", univers: "Cars", description: "La voiture de course la plus rapide de la Piston Cup." },
  { id: "maison_up", nom: "Maison volante", univers: "Là-Haut", description: "La maison de Carl Fredricksen transportée par des milliers de ballons." },
  { id: "noix_coco", nom: "Kakamora", univers: "Vaiana", description: "Un petit pirate en armure de noix de coco venant du Pacifique." },
  { id: "bouclier", nom: "Bouclier de Captain America", univers: "Marvel", description: "Un disque indestructible en vibranium, symbole de justice." },
  { id: "gantelet", nom: "Gantelet de l'Infini", univers: "Marvel", description: "Une armure capable de contenir les six Pierres de l'Infini." },
  { id: "marteau", nom: "Mjölnir (Marteau de Thor)", univers: "Marvel", description: "Seuls ceux qui en sont dignes peuvent soulever ce marteau divin." },
  { id: "sabre", nom: "Sabre laser", univers: "Star Wars", description: "L'arme élégante des chevaliers Jedi et des seigneurs Sith." },
  { id: "casque_vader", nom: "Casque de Dark Vador", univers: "Star Wars", description: "L'armure respiratoire imposante du Seigneur Noir des Sith." },
  { id: "faucon", nom: "Faucon Millenium", univers: "Star Wars", description: "Le vaisseau spatial le plus rapide de la galaxie (en 12 parsecs)." },
  { id: "grogu", nom: "Berceau de Grogu", univers: "Star Wars / Mandalorian", description: "Le berceau flottant protégeant 'L'Enfant'." },
  { id: "chapeau_woody", nom: "Chapeau de Woody", univers: "Toy Story", description: "Le chapeau de cow-boy du plus célèbre des jouets." },
  { id: "fourchette", nom: "Fourchette", univers: "Toy Story 4", description: "Un projet artisanal devenu le jouet préféré de Bonnie." },
  { id: "porte_monstre", nom: "Porte de Boo", univers: "Monstres & Cie", description: "Un portail magique reliant le monde des monstres à la chambre d'un enfant." },
  { id: "miroir", nom: "Miroir Magique", univers: "Blanche-Neige", description: "Un miroir qui dit toujours la vérité sur la beauté." },
  { id: "glace", nom: "Glace Mickey", univers: "Parcs Disney", description: "La célèbre gourmandise glacée en forme de tête de Mickey." },
  { id: "oreille_mickey", nom: "Serre-tête Oreilles", univers: "Parcs Disney", description: "L'accessoire indispensable pour toute visite à Disneyland." }
];